dict = {
  '': '',
  'detective': 'Crime',
  'northern': 'Regional',
  'historical': 'Drama',
  'non-narrative': 'Experimental',
  'tragicomedy': 'Comedy',
  'extreme sports': 'Sports',
  'teen': 'Drama',
  'sexploitation': 'Erotic',
  'women in prison films': 'Drama',
  'short film': 'Short',
  'roadshow/carny': 'Adventure',
  'stoner': 'Comedy',
  'female buddy film': 'Comedy',
  'revenge': 'Action',
  'noir fiction': 'Noir',
  'revisionist fairy tale': 'Fantasy',
  'beach party film': 'Comedy',
  'medical fiction': 'Drama',
  'space western': 'Sci-Fi',
  'werewolf fiction': 'Horror',
  'singing cowboy': 'Western',
  'parkour in popular culture': 'Sports',
  'interpersonal relationships': 'Drama',
  'mystery play': 'Mystery',
  'biopic [feature]': 'Biography',
  'comedy thriller': 'Comedy',
  'dystopia': 'Sci-Fi',
  'crime': 'Crime',
  'feature film': 'General',
  'christian film': 'Religious',
  'gay pornography': 'Erotic',
  'neorealism': 'Drama',
  'kafkaesque': 'Drama',
  'pornography': 'Erotic',
  'history': 'Historical',
  'comdedy': 'Comedy',
  'essay': 'Documentary',
  'alternate history': 'Sci-Fi',
  'alien film': 'Sci-Fi',
  'new hollywood': 'Drama',
  'ghost': 'Horror',
  'technofantasy': 'Sci-Fi',
  'british new wave': 'Drama',
  'political drama': 'Political',
  'reality': 'Reality',
  'sword-and-sandal': 'Adventure',
  'dance': 'Musical',
  'robinsonade': 'Adventure',
  'romantic drama': 'Romance',
  'ethnofiction': 'Drama',
  'fictional character': 'Drama',
  'apocalyptic': 'Sci-Fi',
  'metafiction': 'Experimental',
  'action fiction': 'Action',
  'prison film': 'Drama',
  'slapstick': 'Comedy',
  'docudrama': 'Documentary',
  'cosmic horror': 'Horror',
  'political': 'Political',
  'adult': 'General',
  'film adaptation': 'Adaptation',
  'vampire': 'Horror',
  'baseball': 'Sports',
  'gay interest': 'LGBTQ',
  'acid western': 'Western',
  'christian fiction': 'Religious',
  'comedy-drama': 'Comedy',
  'road-horror': 'Horror',
  'athletics': 'Sports',
  'sci fi pictures original films': 'Sci-Fi',
  'foreign legion': 'Drama',
  'early black cinema': 'Black cinema',
  'epic western': 'Western',
  'lgbt': 'LGBTQ',
  'lesbian-related': 'LGBTQ',
  'spy': 'Crime',
  'pinku eiga': 'Exploitation',
  'sports': 'Sports',
  'parody': 'Comedy',
  'historical fiction': 'Historical',
  'bengali cinema': 'Regional',
  'workplace comedy': 'Comedy',
  'animated documentary': 'Animation',
  'gender issues': 'Drama',
  'christian art': 'Religious',
  'creature film': 'Horror',
  'revisionist western': 'Western',
  'score': 'Music',
  'b-movie': 'Exploitation',
  'social problem film': 'Drama',
  'fantasy': 'Fantasy',
  'biker film': 'Adventure',
  'comedy of manners': 'Comedy',
  'outlaw': 'Crime',
  'film': 'General',
  'indie': 'Independent',
  'three kingdoms': 'Drama',
  'alternative rock': 'Music',
  'autobiographical': 'Biography',
  'crime drama': 'Crime',
  'genre art': 'Art',
  'i music': 'Music',
  'comical satyre': 'Comedy',
  'supermarionation': 'Animation',
  'psycho-biddy': 'Horror',
  'drama fiction': 'Drama',
  'surrealism': 'Experimental',
  'sageuk': 'Historical',
  'buddy picture': 'Comedy',
  'soul': 'Music',
  'film-opera': 'Musical',
  'thriller': 'Thriller',
  'kitchen sink realism': 'Drama',
  'screwball comedy': 'Comedy',
  'c-movie': 'Exploitation',
  'action thrillers': 'Action',
  'educational': 'Educational',
  'science fiction western': 'Sci-Fi',
  'essay film': 'Documentary',
  'war': 'War',
  'pop music': 'Music',
  'journalism': 'Drama',
  'neo-noir': 'Noir',
  'inspirational drama': 'Drama',
  'folk horror': 'Horror',
  'coming-of-age fiction': 'Drama',
  'found footage': 'Horror',
  'financial thriller': 'Thriller',
  'business': 'Drama',
  'military fiction': 'War',
  'comic book': 'Graphic Novel',
  'graphic & applied arts': 'Art',
  'short': 'Short',
  'chinese movies': 'Regional',
  'biopunk': 'Sci-Fi',
  'sword and sorcery': 'Adventure',
  'cmc pictures': 'General',
  'pornographic movie': 'Erotic',
  'popular science': 'Science',
  'media satire': 'Comedy',
  'survival': 'Adventure',
  'road movie': 'Adventure',
  'gangster film': 'Crime',
  'comedy film': 'Comedy',
  'master criminal films': 'Crime',
  'cantopop': 'Music',
  'comedy horror': 'Comedy',
  'swashbuckler films': 'Adventure',
  'horror comedy': 'Comedy',
  'supernatural': 'Horror',
  'masala': 'Drama',
  'vigilante': 'Action',
  'j-pop': 'Music',
  'bdsm-themed': 'Erotic',
  'protest art': 'Political',
  'comedy western': 'Comedy',
  'future noir': 'Noir',
  'black comedy': 'Comedy',
  'zombie film': 'Horror',
  'superhero movie': 'Superhero',
  'biographical film': 'Biography',
  'christian': 'Religious',
  'homoeroticism': 'LGBT',
  'satyr play': 'Ancient',
  'action': 'Action',
  'splatter film': 'Horror',
  'sex comedy': 'Comedy',
  'animated': 'Animation',
  "children's": 'Children/Family',
  'chick flick': 'Romance',
  'music-themed': 'Music',
  'fantasy comedy': 'Comedy',
  'archaeology': 'Historical',
  'pirate': 'Adventure',
  'ensemble film': 'Drama',
  'behind-the-scenes': 'Documentary',
  "children's entertainment": 'Children/Family',
  'police procedural': 'Crime',
  'cold war': 'War',
  'beach film': 'Adventure',
  'courtroom drama': 'Drama',
  'drama': 'Drama',
  'backstage musical': 'Musical',
  'gangster': 'Crime',
  'boxing': 'Sports',
  'ninja': 'Action',
  'combat films': 'War',
  'czechoslovak new wave': 'Regional',
  'world cinema': 'General',
  'sci-fi adventure': 'Sci-Fi',
  'culture & society': 'Drama',
  'robbery': 'Crime',
  'religious satire': 'Religious',
  'war film': 'War',
  'neo-western': 'Western',
  'environmental science': 'Science',
  "children's fantasy": 'Fantasy',
  'comedy': 'Comedy',
  'hood': 'Drama',
  'childhood drama': 'Drama',
  'autobiography': 'Biography',
  'absurdism': 'Experimental',
  'monster': 'Horror',
  'fairy tale': 'Fantasy',
  'sport': 'Sports',
  'courtroom comedy': 'Comedy',
  'science fantasy': 'Sci-Fi',
  'star vehicle': 'Drama',
  'finance & investing': 'Business',
  'auto racing': 'Sports',
  'ealing comedies': 'Comedy',
  'art film': 'Art',
  'romantic novel': 'Romance',
  'costume horror': 'Horror',
  'satanic': 'Horror',
  'experimental film': 'Experimental',
  'buddy cop': 'Action',
  'polar': 'Adventure',
  'horror fiction': 'Horror',
  'horror': 'Horror',
  'health & fitness': 'Documentary',
  'tamil cinema': 'Regional',
  'uchronia': 'Sci-Fi',
  'softcore porn': 'Erotic',
  'biographical': 'Biography',
  'romance film': 'Romance',
  'bloopers & candid camera': 'Comedy',
  'absurdist fiction': 'Experimental',
  'silent film': 'Silent',
  'fan film': 'Fan Film',
  'archives and records': 'Documentary',
  'medieval': 'Historical',
  'gothic': 'Horror',
  'stop motion': 'Animation',
  'muckraker': 'Drama',
  'remake': 'General',
  'gothic film': 'Horror',
  'feature': 'General',
  'heroic bloodshed': 'Action',
  'opera': 'Musical',
  'gay themed': 'LGBT',
  'detective fiction': 'Detective',
  'erotic thriller': 'Erotic',
  'romantic thriller': 'Romance',
  'musical drama': 'Musical',
  'anti-war film': 'War',
  'film noir': 'Noir',
  'patriotic film': 'Drama',
  'epic': 'Drama',
  'punk rock': 'Music',
  'techno-thriller': 'Thriller',
  'linguistics': 'Documentary',
  'puppet': 'Animation',
  'operetta': 'Musical',
  'concert': 'Music',
  'doomsday film': 'Sci-Fi',
  'mockbuster': 'Comedy',
  'psychedelic': 'Music',
  'indian western': 'Regional',
  'propaganda': 'Political',
  'dystopian': 'Sci-Fi',
  'nonlinear narrative': 'Drama',
  'humour': 'Comedy',
  'splatter': 'Horror',
  'reboot': 'General',
  'interactive': 'Interactive',
  'gross out': 'Comedy',
  'mystery fiction': 'Mystery',
  'holiday-themed': 'Drama',
  'fantasy anime': 'Animation',
  'independent': 'Independent',
  'mythological fantasy': 'Fantasy',
  'school story': 'Drama',
  'giallo': 'Mystery',
  'caper story': 'Crime',
  'breakdance': 'Music',
  'war effort': 'War',
  'thriller play': 'Thriller',
  'samurai cinema': 'Action',
  'libraries and librarians': 'Drama',
  'bildungsroman': 'Drama',
  'pink': 'Erotic',
  'live action': 'Live Action',
  'mormon cinema': 'Religious',
  'space drama': 'Sci-Fi',
  'costume adventure': 'Adventure',
  'silhouette animation': 'Animation',
  'latino': 'Regional',
  'crime comedy': 'Comedy',
  '[': '',
  'instrumental music': 'Music',
  'fan edit': 'Fan Film',
  'fan': 'Drama',
  'historical epic': 'Historical',
  'slice of life story': 'Drama',
}

request2 = {
    "progressive rock": "Music",
    "crime thriller": "Thriller",
    "black-and-white": "Experimental",
    "martial arts film": "Action",
    "heaven-can-wait fantasies": "Fantasy",
    "psychological thriller": "Thriller",
    "illnesses & disabilities": "Drama",
    "travel": "Adventure",
    "biblical genre": "Religious",
    "media studies": "Documentary",
    "exploitation": "Drama",
    "cult": "Drama",
    "music": "Music",
    "comedy drama": "Comedy",
    "nuclear warfare": "Drama",
    "experimental": "Experimental",
    "social": "Drama",
    "disaster": "Thriller",
    "western": "Action",
    "apocalyptic and post-apocalyptic fiction": "Sci-Fi",
    "education": "Documentary",
    "mafia": "Crime",
    "musical": "Music",
    "concert film": "Music",
    "transgender": "LGBTQ",
    "tollywood": "Film Industry",
    "musical comedy": "Comedy",
    "sword and sorcery films": "Fantasy",
    "action comedy": "Comedy",
    "the netherlands in world war ii": "Historical",
    "hip hop movies": "Music",
    "romance": "Romance",
    "zombie comedy": "Comedy",
    "family-oriented adventure": "Adventure",
    "anthropology": "Documentary",
    "magic realism": "Fantasy",
    "science fiction": "Sci-Fi",
    "historical drama": "Drama",
    "family & personal relationships": "Drama",
    "action movies": "Action",
    "plague": "Drama",
    "fictional film": "Fiction",
    "children's/family": "Children's",
    "period": "Historical",
    "animals": "Documentary",
    "nature documentary": "Documentary",
    "bushranging": "Action",
    "trial": "Drama",
    "fantasy drama": "Fantasy",
    "nature": "Documentary",
    "jidaigeki": "Historical",
    "existentialism": "Drama",
    "sponsored film": "Documentary",
    "psychological": "Thriller",
    "post-apocalyptic fiction": "Sci-Fi",
    "political documetary": "Documentary",
    "movies about gladiators": "Historical",
    "slasher": "Horror",
    "comedy of errors": "Comedy",
    "spoken drama": "Drama",
    "natural disaster": "Thriller",
    "goat gland": "Experimental",
    "adventure": "Adventure",
    "sci-fi horror": "Horror",
    "art": "Documentary",
    "roadshow theatrical release": "Theatrical",
    "sword and sandal": "Action",
    "coming of age": "Drama",
    "animated cartoon": "Animation",
    "historical documentaries": "Documentary",
    "political thriller": "Thriller",
    "spaghetti western": "Action",
    "outlaw biker film": "Action",
    "albino bias": "Drama",
    "supernatural fiction": "Fantasy",
    "police": "Crime",
    "holiday film": "Comedy",
    "political cinema": "Political",
    "computer animation": "Animation",
    "prequel": "Film Format",
    "japanese mythology": "Fantasy",
    "surreal humour": "Comedy",
    "silent": "Historical",
    "animated musical": "Animation",
    "gay": "LGBTQ",
    "political satire": "Political",
    "erotic drama": "Drama",
    "romantic fantasy": "Romance",
    "anti-war": "War",
    "biography": "Biography",
    "animal picture": "Documentary",
    "cavalry film": "Historical",
    "sports documentary": "Documentary",
    "period piece": "Historical",
    "airplanes and airports": "Adventure",
    "film & television history": "Documentary",
    "psychological horror": "Horror",
    "conspiracy fiction": "Thriller",
    "halloween": "Holiday",
    "computers": "Technology",
    "sports drama": "Drama",
    "contemporary fantasy": "Fantasy",
    "addiction drama": "Drama",
    "movie serial": "Film Format",
    "pornographic": "Adult",
    "aqua-musical": "Music",
    "law & crime": "Crime",
    "clay animation": "Animation",
    "poverty porn": "Drama",
    "lgbt-related": "LGBTQ",
    "domestic comedy": "Comedy",
    "television movie": "Film Format",
    "blaxploitation": "Drama",
    "weird west": "Western",
    "feminist film": "Drama",
    "dogme 95": "Drama",
    "tokusatsu": "Action",
    "action thriller": "Thriller",
    "superhero": "Action",
    "religious film": "Religious",
    "family drama": "Drama",
    "race movie": "Drama",
    "filmed play": "Drama",
    "hagiography": "Religious",
    "adventure comedy": "Comedy",
    "gross-out film": "Comedy",
    "americana": "Genre",
    "hybrid western": "Western",
    "legend": "Fantasy",
    "religious": "Religious",
    "docufiction": "Documentary",
    "student": "Documentary",
    "historical fantasy": "Fantasy",
    "escape film": "Action",
    "metacinema": "Experimental",
    "world history": "Documentary",
    "statutory rape": "Drama",
    "marriage drama": "Drama",
    "romantic comedy": "Romance",
    "surrealist cinema": "Experimental",
    "social issues": "Drama",
    "avant-garde": "Experimental",
    "expressionism": "Art",
    "bruceploitation": "Action",
    "intersex": "LGBTQ",
    "fiction": "Fiction",
    "buddy": "Comedy",
    "vampire movies": "Horror",
    "horse racing": "Documentary",
    "chinese animation": "Animation",
    "cannibal": "Horror",
    "social drama": "Drama",
    "zombie": "Horror",
    "werewolf": "Horror",
    "dystopian fiction": "Sci-Fi",
    "sci-fi thriller": "Thriller",
    "camp": "Comedy",
    "jungle film": "Adventure",
    "legal drama": "Drama",
    "gay romance": "Romance",
    "crossover fiction": "Fiction",
    "rural drama": "Drama",
    "coming-of-age": "Drama",
    "b-western": "Western",
    "pop rock": "Music",
    "film à clef": "Drama",
    "alien invasion": "Sci-Fi",
    "screenlife": "Experimental",
    "heavenly comedy": "Comedy",
    "mystery": "Thriller",
    "cyberpunk": "Sci-Fi",
    "filipino": "Film Industry",
    "family film": "Children's",
    "erotic": "Adult",
    "noir": "Thriller",
    "christmas movie": "Holiday",
    "swashbuckler": "Action",
    "language & literature": "Documentary",
    "space opera": "Sci-Fi",
    "steampunk": "Sci-Fi",
    "filipino movies": "Film Industry",
    "british empire film": "Historical",
    "fantasy adventure": "Adventure",
    "yaoi": "LGBTQ",
    "rockumentary": "Music",
    "malayalam cinema": "Film Industry",
    "anime": "Animation",
    "juvenile delinquency film": "Drama",
    "tragedy": "Drama",
    "whodunit": "Mystery",
    "stand-up comedy": "Comedy",
    "action/adventure": "Action",
    "erotica": "Adult",
    "hardcore pornography": "Adult",
    "sámi": "Documentary",
    "japanese movies": "Film Industry",
    "animation": "Animation",
    "romantic fiction": "Romance",
    "jukebox musical": "Music",
    "coming-of-age film": "Drama",
    "pseudo-documentary": "Documentary",
    "collage": "Art",
    "prison escape": "Action",
    "flashback": "Narrative",
    "action-adventure": "Action",
    "gulf war": "Historical",
    "pre-code": "Historical",
    "bollywood": "Film Industry",
    "new queer cinema": "LGBTQ",
    "mysticism": "Fantasy",
    "one-shot": "Experimental",
    "adult animation": "Animation",
    "monster movie": "Horror",
    "costume drama": "Historical",
    "dieselpunk": "Sci-Fi",
    "melodrama": "Drama",
    "therimin music": "Music",
    "natural horror films": "Horror",
    "buddy film": "Comedy",
    "demonic child": "Horror",
    "children's issues": "Drama",
    "urban fantasy": "Fantasy",
    "chase movie": "Action",
    "anthology": "Drama",
    "propaganda film": "Political",
    "mondo film": "Documentary",
    "christmas": "Holiday",
    "point of view shot": "Experimental",
    "kaiju": "Fantasy",
    "gambling": "Drama",
    "private military company": "Action",
    "period horror": "Horror",
    "true crime": "Documentary",
    "post-apocalyptic": "Sci-Fi",
    "documentary": "Documentary",
    "xiaoshuo": "Literary",
    "satire": "Comedy",
    "mumblecore": "Drama",
    "crime fiction": "Crime",
    "mockumentary": "Documentary",
    "heist": "Crime",
    "adaptation": "Drama",
    "time travel": "Sci-Fi",
    "pritcha": "Drama",
    "z movie": "Genre",
    "family": "Family",
    "stoner film": "Comedy",
    "rock music": "Music",
    "inventions & innovations": "Documentary",
    "suspense": "Thriller",
    "time-travel": "Sci-Fi",
    "environmental": "Documentary",
    "ninja movie": "Action",
    "haunted house film": "Horror",
    "blockbuster": "Film Format",
    "news": "Documentary",
    "glamorized spy film": "Spy",
    "prison": "Drama",
    "wuxia": "Action",
    "dark fantasy": "Fantasy",
    "triathlon s": "Sports",
    "mashup": "Experimental",
    'speculative fiction' : 'Sci-Fi',
    ']' : '',
    'LGBT-related' : 'LGBTQ',
    'children/family' : 'Children/Family',
    'lgbtq' : 'LGBTQ',
    'other' : '',
    'sci-fi' : 'Sci-Fi',
    'action' : 'Action'
 }




genre_categories_cmu = {
    "Documentary": [
        "Biography", "Documentary", "Concert film", "Docudrama",
        "Historical Documentaries", "Political Documentary", "Sponsored film",
        "Mondo film", "Essay Film", "Educational", "News", "Media Studies",
        "Anthropology", "Archaeology", "World History", "Environmental Science",
        "Film & Television History", "Political Documetary", "Journalism", "Education"
    ],
    "Action & Adventure": [
        "Action", "Adventure", "Action/Adventure", "Wuxia", "Martial Arts Film", "Spy", "Combat Films", "Fantasy Adventure",
        "Sword and sorcery", "Sword and sorcery films", "Chase Movie", "Heist",
        "Road movie", "Prison escape", "Alien invasion", "Road-Horror",
        "Swashbuckler films", "Sword and Sandal", "Revenge", "Cavalry Film",
        "Superhero", "Superhero movie", "Indian Western", "Revisionist Western",
        "Epic Western", "B-Western", "Hybrid Western", "Spaghetti Western",
        "Action Comedy", "Caper story", "Singing cowboy", "Northern", "Western",
        "Glamorized Spy Film", "Samurai cinema", "Private military company", "Race movie"
    ],
    "Comedy": [
        "Comedy", "Black comedy", "Parody", "Satire", "Comedy film",
        "Romantic comedy", "Adventure Comedy", "Comedy-drama", "Comedy of manners",
        "Gross-out film", "Gross out", "Slapstick", "Mockumentary", "Buddy film",
        "Stoner film", "Comedy Thriller", "Domestic Comedy", "Screwball comedy",
        "Workplace Comedy", "Heavenly Comedy", "Sex comedy", "Bloopers & Candid Camera",
        "Chick flick", "Buddy Picture", "Courtroom Comedy", "Comedy Western",
        "Comedy of Errors", "Comedy horror", "Fantasy Comedy", "Female buddy film",
        "Stand-up comedy","Ealing Comedies", "Media Satire"
    ],
    "Drama": [
        "Drama", "Crime Drama", "Crime Fiction", "Biographical film", "Family Drama",
        "Melodrama", "Political drama", "Marriage Drama", "Coming of age",
        "Coming-of-age film", "Childhood Drama", "Ensemble Film",
        "Juvenile Delinquency Film", "Social problem film", "Addiction Drama",
        "Inspirational Drama", "Teen", "Escape Film", "Courtroom Drama",
        "Legal drama", "Social issues", "Biopic [feature]", "Crime",
        "Kitchen sink realism", "Erotic Drama", "Tragedy", "Tragicomedy",
        "Slice of life story", "Family & Personal Relationships",
        "Interpersonal Relationships", "School story", "Prison", "Prison film"
    ],
    "Fantasy & Sci-Fi": [
        "Science Fiction", "Space western", "Supernatural", "Fantasy",
        "Sci-Fi Adventure", "Sci-Fi Horror", "Sci-Fi Thriller",
        "Apocalyptic and post-apocalyptic fiction", "Space opera", "Cyberpunk",
        "Steampunk", "Alien Film", "Future noir", "Romantic fantasy", "Dystopia",
        "Science fiction Western", "Fantasy Drama", "Mythological Fantasy", "Fairy tale",
        "Time travel", "Sci Fi Pictures original films", "Tokusatsu", "Doomsday film"
    ],
    "Thriller & Mystery": [
        "Thriller", "Mystery", "Crime Thriller", "Psychological thriller",
        "Erotic thriller", "Suspense", "Political thriller", "Romantic thriller",
        "Spy Thriller", "Whodunit", "Conspiracy fiction", "Crime Comedy",
        "Detective fiction", "Master Criminal Films", "Giallo", "Film noir",
        "Detective", "Gangster Film", "Action Thrillers", "Law & Crime"
    ],
    "Horror": [
        "Horror", "Zombie Film", "Slasher", "Creature Film", "Monster movie",
        "Psychological horror", "Natural horror films", "Haunted House Film",
        "Gothic Film", "Demonic child", "Period Horror", "Werewolf fiction",
        "Horror Comedy", "Splatter film", "Costume Horror", "Monster"
    ],
    "Romance": [
        "Romance Film", "Romantic drama", "Romantic comedy", "Chick flick",
        "Homoeroticism", "Romantic thriller"
    ],
    "Historical & Period": [
        "Historical drama", "Costume drama", "Costume Adventure", "Historical Epic",
        "Period piece", "Historical fiction",
          "British Empire Film", "Epic", "Americana",
        "History"
    ],
    "Music & Dance": [
        "Musical", "Musical Drama", "Musical comedy", "Rockumentary",
        "Jukebox musical", "Animated Musical", "Backstage Musical", "Dance",
        "Instrumental Music", "Music", "Punk rock", "Film-Opera", "Hip hop movies","Operetta"
    ],
    "Sports": [
        "Sports", "Boxing", "Baseball", "Extreme Sports", "Auto racing",
        "Horse racing"
    ],
    "Animated & Family": [
        "Animation", "Animated cartoon", "Children's/Family", "Family Film",
        "Children's Fantasy", "Family-Oriented Adventure", "Children's Entertainment",
        "Computer Animation", "Stop motion", "Silhouette animation",
        "Supermarionation", "Clay animation", "Children's", "Holiday Film",
        "Christmas movie", "Anime"
    ],
    "War & Political": [
        "Anti-war", "Anti-war film", "War effort", "Political cinema",
        "Propaganda film", "Political satire", "Cold War", "Nuclear warfare", "Gulf War", "War film", "The Netherlands in World War II", "Media Satire", "Foreign legion"
    ],
    "Experimental & Art": [
        "Art film", "Avant-garde", "Surrealism", "Experimental film",
        "New Hollywood", "Neo-noir", "Existentialism", "Kafkaesque", "Absurdism",
        "Indie", "Dogme 95", "Czechoslovak New Wave", "Expressionism", "Mumblecore",
        "Graphic & Applied Arts"
    ],
    "Religious & Spiritual": [
        "Religious Film", "Christian film", "Hagiography", "Heaven-Can-Wait Fantasies",
        "Feminist Film"
    ],
    "Other": [
        "Live action", "Adult", "Feature film", "Film adaptation", "Language & Literature",
        "Finance & Investing", "Psycho-biddy", "Fan film", "Blaxploitation", "Computers",
        "Film", "Libraries and librarians", "Travel", "Illnesses & Disabilities",
        "Linguistics", "Animals", "Health & Fitness", "Reboot", "Softcore Porn", "Silent film",
        "Short Film", "Gay pornography", "Latino", "Goat gland", "Natural disaster",
        "Travel", "Revisionist Fairy Tale", "Pre-Code", "B-movie", "Z movie",
        "Pornography", "Hardcore pornography", "Sexploitation", 
        "Fictional film", "Inventions & Innovations", "Filmed Play",
        "Women in prison films", "Tollywood", "Airplanes and airports", "Nature",
        "Roadshow theatrical release", "Television movie", "Statutory rape",
        "Pinku eiga", "Cult", "Outlaw biker film", "LGBT", "Roadshow/Carny",
        "Biker Film", "Erotica", "Japanese Movies", "Bengali Cinema", "Albino bias",
        "World cinema", "Glamorized Spy Film", "Pornographic movie", "Animal Picture",
        "Black-and-white", "Filipino Movies", "Disaster", "Early Black Cinema",
        "Jungle Film", "Gay Interest", "Anthology", "Gender Issues", "Business",
        "Culture & Society", "Film \\u00e0 clef","Tamil cinema", "Remake", "Malayalam Cinema", "Bollywood", "Exploitation", "Chinese Movies"
    ]
}
genre_categories = {
    "Documentary": [
        "documentary", "nature documentary", "docudrama", "animated documentary", 
        "rockumentary", "pseudo-documentary", "docufiction", "true crime", "muckraker", 
        "biography", "popular science", "environmental", "reality", "sports documentary", 
        "Archives and records", 'autobiography'
    ],
    "Action & Adventure": [
        "action", "action thriller", "action-adventure", "superhero", "adventure", 
        "spy", "heist", "thriller", "suspense", "swashbuckler", "survival", "vigilante", 
        "heroic bloodshed", "disaster", "space opera", "alien invasion", "road movie",
        "ninja", "prison", "bushranging", "kaiju", "pirate", "buddy", "trial",
        "tokusatsu", "western", "action fiction", "apocalyptic", "Spaghetti Western", 
        "neo-Western", "Action Movies", "Buddy cop", "Acid western", "Bruceploitation", 'robbery', 'hood', 'Ninja movie'
    ],
    "Comedy": [
        "comedy", "romantic comedy", "black comedy", "slapstick", "musical comedy", 
        "comedy drama", "comedy horror", "comedy thriller", "satire", "parody", "dark comedy", 
        "stand-up comedy", "stoner", "mockumentary", "tragicomedy", "surreal humour", 
        "sex comedy", "comical satyre", "Masala", "Humour", "satyr play", 'comic book'
    ],
    "Drama": [
        "drama", "historical drama", "romantic drama", "social drama", "legal drama", 
        "political drama", "drama fiction", "melodrama", "coming-of-age", 
        "coming-of-age fiction", "rural drama",
        "anthology", "social", "teen", "spoken drama", "poverty porn", "magic realism", 'Medical fiction', "Children's Issues", 'Plague', 'tragedy'
    ],
    "Fantasy & Sci-Fi": [
        "fantasy", "dark fantasy", "urban fantasy", "space fantasy", "contemporary fantasy", 
        "fantasy anime", "science fiction", "cyberpunk", "steampunk", "dieselpunk", "space opera", 
        "post-apocalyptic fiction", "dystopian fiction", "alien invasion", "time-travel", 
        "technofantasy", "supernatural", "post-apocalyptic", "speculative fiction", 
        "Supernatural fiction", "fantasy drama", "metafiction", "biopunk", "dystopian", 
        "crossover fiction", "supernatural", "Chinese animation", "uchronia", 
        "Three Kingdoms"
    ],
    "Thriller & Mystery": [
        "thriller", "psychological thriller", "erotic thriller", "financial thriller", 
        "techno-thriller", "mystery", "detective", "whodunit", "noir", "neo-noir", "crime", 
        "gangster", "mystery fiction", "police procedural", "polar", "psychological", 
        "thriller play", "crime fiction", "mafia", "police", "noir fiction", 
        "detective fiction"
    ],
    "Horror": [
        "horror", "psychological horror", "cosmic horror", "folk horror", "vampire", 
        "zombie", "ghost", "slasher", "werewolf", "monster", "giallo", 
        "splatter", "cannibal", "Satanic", "found footage", "paranormal", "horror fiction", 
        "zombie comedy", "Vampire movies"
    ],
    "Romance": [
        "romance", "gay romance", "lesbian-related", "romantic thriller", "romantic drama", 
        "romantic fantasy", "romantic novel", "chick flick", "LGBT-related", "erotic", 
        "erotic thriller", "romantic comedy", "Gay", "Gay Themed"
    ],
    "Historical & Period": [
        "historical", "historical drama", "historical fiction", "period", "alternate history", 
        "legend", "medieval", "sword-and-sandal", "epic", "biographical", "autobiographical", 
        "pseudo-documentary", "Robin Hood", "Jidaigeki", "adaptation", "Mormon cinema", 
        "Beach Party film", "Movies About Gladiators", "Beach Film"
    ],
    "Music & Dance": [
        "musical", "jukebox musical", "rockumentary", "pop music", "concert", "dance", 
        "aqua-musical", "music-themed", "cantopop", "J-pop", "rock music", "pop rock", 
        "progressive rock", "Therimin music", "i music", "opera", 'alternative rock'
    ],
    "Sports": [
        "sport", "sports drama", "boxing", "triathlon", "athletics", "gambling", "wrestling", 
        "triathlon s", "Parkour in popular culture"
    ],
    "Animated & Family": [
        "animated", "anime", "family", "childrens", "puppet", "adult animation", 
        "Christmas", "holiday-themed", "fantasy anime", "children's"
    ],
    "War & Political": [
        "war", "anti-war", "political drama", "political satire", "propaganda", "military", 
        "disaster", "heroic bloodshed", "political", "revolution", "military fiction",  'Patriotic film', 'political thriller'
    ],
    "Experimental & Art": [
        "art", "experimental", "absurdist fiction", "metacinema", "collage", "mashup", 
        "contemporary art", "protest art", "non-narrative", "surrealist cinema", "essay", 
        "fan edit", "alternate history", "screenlife", "short", "silent", 'independent', 
        "mumblecore", "interactive", "behind-the-scenes", "nonlinear narrative", 
        "ethnofiction", "New Queer Cinema", 'Point of view shot'
    ],
    "Religious & Spiritual": [
        "religious", "Christian", "Christian fiction", "spiritual", "religious satire", 
        "Satanic", "Christian art", "soul", "mythology", "biblical genre"
    ],
    "Other": [
        "BDSM-themed", "pornographic", "mockbuster", "student", "fan", "fiction", "pritcha", 
        "Masala", "transgender", "intersex", "live action", "blockbuster", "one-shot", 
        "educational", "CMC Pictures", "Outlaw", 'sexploitation', 'prequel','Sámi', 'Movie serial', 'Film à clef', 'Camp', 'score', 'Bildungsroman'
    ]
}
